on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
name: "Build & Release for development"
jobs:
  build:
    name: Build & Release debug apk
    runs-on: ubuntu-latest #macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.5'
      - run: flutter pub get
      - run: flutter build apk lib/Modules/EntryPointApp/Presentation/Pages/main.dart --debug --split-per-abi
      #- run: |
      #    flutter build ios --no-codesign
      #    cd build/ios/iphoneos
      #    mkdir Payload
      #    cd Payload
      #    ln -s ../Runner.app
      #    cd ..
      #    zip -r app.ipa Payload
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*"
          tag: v1.0.0.${{ github.run_number }}
          token: ${{ secrets.PAT }}
